<?php

namespace Database\Seeders;

use App\Models\RopaRecord;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class RopaSeeder extends Seeder
{
    public function run(): void
    {
        RopaRecord::truncate();

        $now = Carbon::now();

        // ── helpers ──────────────────────────────────────────────────────────
        $sec  = fn(...$v) => $v;
        $date = fn($months) => $months >= 0 ? $now->copy()->addMonths($months) : $now->copy()->subMonths(abs($months));

        // ── RETAIL (20 records, org 1, created_by 2) ─────────────────────────
        $retail = [
            ['RET-001','การสั่งซื้อสินค้าออนไลน์','ฝ่ายขาย','ผจก.ฝ่ายขาย','รับคำสั่งซื้อ จัดส่ง และเก็บประวัติการซื้อของลูกค้า','contract',['ชื่อ-นามสกุล','ที่อยู่','อีเมล','เบอร์โทรศัพท์','ข้อมูลการชำระเงิน'],['ลูกค้าทั่วไป','สมาชิก'],false,[],['บริษัทขนส่ง','ผู้ให้บริการชำระเงิน'],true,false,'','','5 ปี นับจากวันสั่งซื้อ','ตามอายุความทางแพ่ง','Secure Delete',$sec('HTTPS/TLS','Encryption','Access Control/RBAC'),'ระบบ E-Commerce, Stripe','active',-3,9],
            ['RET-002','การส่งอีเมลการตลาด','ฝ่ายการตลาด','ผจก.การตลาด','ส่งโปรโมชันและข้อเสนอพิเศษให้ลูกค้าที่ยินยอม','consent',['อีเมล','ชื่อ','ประวัติการซื้อ'],['ลูกค้าที่ให้ความยินยอม'],false,[],['Mailchimp'],true,true,'สหรัฐอเมริกา','Standard Contractual Clauses (SCCs)','1 ปี หรือจนถอนความยินยอม','','Anonymize',$sec('API Key','Data Minimization'),'Mailchimp','active',-6,6],
            ['RET-003','การบริหารทรัพยากรบุคคล','ฝ่าย HR','ผจก. HR','จัดการสัญญาจ้าง เงินเดือน สวัสดิการ ภาษีพนักงาน','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','เงินเดือน','บัญชีธนาคาร','ข้อมูลภาษี'],['พนักงาน','ผู้สมัครงาน'],false,[],['กรมสรรพากร','ประกันสังคม','ธนาคาร'],true,false,'','','10 ปี หลังสิ้นสุดสัญญาจ้าง','ตาม พ.ร.บ.คุ้มครองแรงงาน','Shredding',$sec('Access Control/RBAC','Encryption','Audit Log'),'SAP HR Module','active',-2,12],
            ['RET-004','โปรแกรมสะสมแต้ม Loyalty','ฝ่ายการตลาด','ผจก.ดิจิทัล','บริหารคะแนนสะสม แลกของรางวัล และวิเคราะห์พฤติกรรม','consent',['ชื่อ','อีเมล','เบอร์โทรศัพท์','ประวัติการซื้อ','ความสนใจ'],['สมาชิก Loyalty'],false,[],['บริษัทพันธมิตร'],true,false,'','','3 ปี หลังยกเลิกสมาชิก','','Secure Delete',$sec('Encryption','Access Control/RBAC'),'Salesforce Loyalty','active',-1,11],
            ['RET-005','การวิเคราะห์พฤติกรรมลูกค้า (Analytics)','ฝ่าย Data Analytics','หัวหน้า Data','วิเคราะห์รูปแบบการซื้อเพื่อปรับปรุงบริการ','legitimate_interest',['Cookie/Tracking','IP Address','ประวัติการซื้อ'],['ผู้เยี่ยมชมเว็บไซต์'],false,[],['Google Analytics'],true,true,'สหรัฐอเมริกา','SCCs','1 ปี','','Anonymize',$sec('Data Minimization','Anonymization'),'Google Analytics 4','active',-4,8],
            ['RET-006','การบันทึกกล้องวงจรปิด (CCTV)','ฝ่ายรักษาความปลอดภัย','หัวหน้ารักษาความปลอดภัย','ป้องกันการโจรกรรมและเพื่อความปลอดภัยในร้าน','legitimate_interest',['ภาพถ่าย','ข้อมูลตำแหน่ง (GPS)'],['บุคคลภายนอกอื่นๆ','พนักงาน'],false,[],[],false,false,'','','30 วัน','ยกเว้นกรณีเกิดเหตุ','Overwrite',$sec('Physical Access Control','Encryption'),'NVR ระบบ CCTV','active',-1,13],
            ['RET-007','การส่ง SMS โปรโมชัน','ฝ่ายการตลาด','ผจก.การตลาด','ส่ง SMS โปรโมชันและแจ้งเตือนสินค้าให้ลูกค้า','consent',['เบอร์โทรศัพท์','ชื่อ'],['ลูกค้าที่ให้ความยินยอม'],false,[],['ผู้ให้บริการ SMS Gateway'],true,false,'','','1 ปี หลังถอนความยินยอม','','Secure Delete',$sec('API Key Authentication'),'DTAC SMS Gateway','active',-3,9],
            ['RET-008','การจัดการข้อร้องเรียนลูกค้า','ฝ่ายบริการลูกค้า','ผจก.ลูกค้าสัมพันธ์','รับและแก้ไขข้อร้องเรียนตาม พ.ร.บ.คุ้มครองผู้บริโภค','legal_obligation',['ชื่อ-นามสกุล','อีเมล','เบอร์โทรศัพท์'],['ลูกค้าทั่วไป'],false,[],[],false,false,'','','5 ปี','ตาม พ.ร.บ.คุ้มครองผู้บริโภค','Secure Delete',$sec('Access Control/RBAC','Audit Log'),'CRM Zendesk','active',-5,7],
            ['RET-009','การรับสมัครพนักงาน','ฝ่าย HR','ผจก. HR','เก็บใบสมัครและประเมินผู้สมัคร','legitimate_interest',['ชื่อ-นามสกุล','อีเมล','เบอร์โทรศัพท์','ประวัติการทำงาน'],['ผู้สมัครงาน'],false,[],['JobsDB','LinkedIn'],true,false,'','','1 ปี หลังสิ้นสุดกระบวนการสรรหา','','Secure Delete',$sec('Access Control/RBAC'),'JobsDB ATS','active',-2,10],
            ['RET-010','การตรวจสอบการทุจริต (Fraud Detection)','ฝ่าย IT Security','CISO','ตรวจจับธุรกรรมผิดปกติและป้องกันการโจรกรรม','legitimate_interest',['IP Address','ข้อมูลการชำระเงิน','Cookie/Tracking'],['ลูกค้าทั่วไป','สมาชิก'],false,[],['Stripe Radar'],true,true,'สหรัฐอเมริกา','SCCs','90 วัน','','Secure Delete',$sec('Encryption','Firewall','Intrusion Detection (IDS/IPS)'),'Stripe Radar, ML Model','active',-1,11],
            ['RET-011','การบริหารสัญญาซัพพลายเออร์','ฝ่ายจัดซื้อ','ผจก.จัดซื้อ','จัดการสัญญาและข้อมูลติดต่อคู่ค้า','contract',['ชื่อ-นามสกุล','อีเมล','เบอร์โทรศัพท์'],['คู่ค้า/ซัพพลายเออร์'],false,[],[],false,false,'','','5 ปี หลังสิ้นสุดสัญญา','','Shredding',$sec('Access Control/RBAC'),'SAP Procurement','active',-6,6],
            ['RET-012','การเชื่อมต่อ Marketplace','ฝ่ายขายออนไลน์','ผจก.ขายออนไลน์','ซิงค์ข้อมูลสินค้าและคำสั่งซื้อกับ Lazada/Shopee','contract',['ชื่อ-นามสกุล','ที่อยู่จัดส่ง'],['ลูกค้าทั่วไป'],false,[],['Lazada','Shopee'],true,false,'','','3 ปี','','Secure Delete',$sec('API Key Authentication','HTTPS/TLS'),'Multichannel Platform','active',-3,9],
            ['RET-013','การรายงานภาษีมูลค่าเพิ่ม (VAT)','ฝ่ายบัญชี','CFO','ยื่นแบบภาษี VAT และรายงานทางการเงิน','legal_obligation',['ชื่อ-นามสกุล','เลขผู้เสียภาษี'],['คู่ค้า/ซัพพลายเออร์','ลูกค้าองค์กร'],false,[],['กรมสรรพากร'],true,false,'','','5 ปี ตามกฎหมายภาษี','ตาม พ.ร.บ.บัญชี','Shredding',$sec('Access Control/RBAC','Audit Log'),'SAP FICO','active',-4,8],
            ['RET-014','การให้บริการ Click & Collect','ฝ่ายบริการลูกค้า','ผจก.บริการลูกค้า','รับจองสินค้าออนไลน์รับที่สาขา','contract',['ชื่อ-นามสกุล','เบอร์โทรศัพท์','อีเมล'],['ลูกค้าทั่วไป'],false,[],[],false,false,'','','1 ปี','','Secure Delete',$sec('HTTPS/TLS','Access Control/RBAC'),'ระบบ OMS','draft',0,12],
            ['RET-015','การวิเคราะห์ Social Media','ฝ่ายการตลาด','หัวหน้า Social Media','วิเคราะห์ความคิดเห็นและเทรนด์บน Social Media','legitimate_interest',['ข้อมูลสาธารณะ Social Media'],['บุคคลภายนอกอื่นๆ'],false,[],['Hootsuite'],true,true,'สหรัฐอเมริกา','SCCs','6 เดือน','','Anonymize',$sec('Data Minimization'),'Hootsuite, Brandwatch','active',-2,10],
            ['RET-016','การส่งสินค้าระหว่างประเทศ','ฝ่ายโลจิสติกส์','ผจก.โลจิสติกส์','จัดส่งสินค้าไปต่างประเทศและพิธีการศุลกากร','contract',['ชื่อ-นามสกุล','ที่อยู่','เลขบัตรประชาชน'],['ลูกค้าทั่วไป'],false,[],['DHL','FedEx','กรมศุลกากร'],true,true,'หลายประเทศ','Standard Business Terms','7 ปี ตามกฎหมายศุลกากร','','Shredding',$sec('HTTPS/TLS','Encryption'),'SAP TM, DHL API','active',-5,7],
            ['RET-017','การให้บริการบัตรกำนัล (Gift Card)','ฝ่ายการเงิน','CFO','ออกและบริหารบัตรกำนัลสำหรับลูกค้า','contract',['ชื่อ','อีเมล'],['ลูกค้าทั่วไป'],false,[],[],false,false,'','','3 ปี หลังบัตรหมดอายุ','','Secure Delete',$sec('Encryption','Access Control/RBAC'),'Gift Card Platform','active',-1,11],
            ['RET-018','การจัดการโปรแกรมพันธมิตร (Affiliate)','ฝ่ายการตลาด','ผจก.การตลาด','บริหารค่าคอมมิชชั่นและข้อมูลผู้แนะนำสินค้า','contract',['ชื่อ-นามสกุล','บัญชีธนาคาร','อีเมล'],['คู่ค้า/ซัพพลายเออร์'],false,[],[],false,false,'','','5 ปี หลังสิ้นสุดสัญญา','','Secure Delete',$sec('Access Control/RBAC','Audit Log'),'Affiliate Platform','under_review',-14,2],
            ['RET-019','การทำ Remarketing โฆษณา','ฝ่ายการตลาดดิจิทัล','ผจก.ดิจิทัล','แสดงโฆษณาแบบ Personalized แก่ผู้เยี่ยมชม','consent',['Cookie/Tracking','IP Address'],['ผู้เยี่ยมชมเว็บไซต์'],false,[],['Meta','Google'],true,true,'สหรัฐอเมริกา','SCCs','90 วัน','','Anonymize',$sec('Consent Management','Data Minimization'),'Meta Pixel, Google Ads','active',-3,9],
            ['RET-020','การป้องกันบัญชีผู้ใช้ (Account Security)','ฝ่าย IT Security','CISO','ป้องกันการเข้าถึงบัญชีโดยไม่ได้รับอนุญาต','legitimate_interest',['IP Address','Cookie/Tracking','อีเมล'],['สมาชิก'],false,[],[],false,false,'','','1 ปี','','Secure Delete',$sec('Multi-Factor Authentication','Firewall','Audit Log'),'Auth0, WAF','active',-2,10],
        ];

        // ── HOSPITAL (20 records, org 2, created_by 6) ────────────────────────
        $hospital = [
            ['MED-001','บันทึกประวัติการรักษา','ฝ่ายเวชระเบียน','หน.เวชระเบียน','บันทึกประวัติการรักษา วินิจฉัยโรค และติดตามผล','consent',['ชื่อ-นามสกุล','วันเกิด','เลขบัตรประชาชน','ข้อมูลสุขภาพ'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['แพทย์ผู้รักษา','บริษัทประกัน'],true,false,'','','10 ปี หลังผู้ป่วยครบ 18 ปี','ตาม พ.ร.บ.สถานพยาบาล','Shredding',$sec('Role-based Access','Encryption','Audit Log','Regular Backup'),'HIS (Hospital Information System)','active',-3,9],
            ['MED-002','การให้บริการห้องฉุกเฉิน (ER)','ฝ่ายฉุกเฉิน','หน.ฝ่ายฉุกเฉิน','รักษาผู้ป่วยฉุกเฉินและบันทึกการปฐมพยาบาล','vital_interest',['ชื่อ-นามสกุล','ข้อมูลสุขภาพ','เบอร์โทรศัพท์'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],[],false,false,'','','10 ปี','ตาม พ.ร.บ.สถานพยาบาล','Shredding',$sec('Role-based Access','Encryption'),'HIS, PACS','active',-2,10],
            ['MED-003','การนัดหมายแพทย์ออนไลน์','ฝ่ายบริการผู้ป่วย','ผจก.บริการ','ให้ผู้ป่วยนัดหมายแพทย์ผ่านแอปและเว็บ','contract',['ชื่อ-นามสกุล','เบอร์โทรศัพท์','อีเมล','วันเกิด'],['ผู้ป่วย'],false,[],[],false,false,'','','2 ปี','','Secure Delete',$sec('HTTPS/TLS','Authentication'),'แอปพลิเคชันโรงพยาบาล','active',-1,11],
            ['MED-004','การเบิกจ่ายประกันสุขภาพ','ฝ่ายการเงิน','ผจก.การเงิน','ส่งข้อมูลค่ารักษาให้บริษัทประกันเพื่อเบิกจ่าย','contract',['ชื่อ-นามสกุล','เลขกรมธรรม์','ข้อมูลสุขภาพ','ค่ารักษา'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['บริษัทประกัน','สปสช.'],true,false,'','','7 ปี','ตามกฎหมายประกันภัย','Shredding',$sec('Encryption','Secure File Transfer','Audit Log'),'Claim Management System','active',-4,8],
            ['MED-005','การวิจัยทางคลินิก','ฝ่ายวิจัย','หน.ฝ่ายวิจัย','ทดลองยาและการรักษาใหม่ตามมาตรฐาน GCP','consent',['ชื่อ-นามสกุล','ข้อมูลสุขภาพ','ผลตรวจ Lab'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์','ข้อมูลพันธุกรรม'],['สถาบันวิจัย','อย.'],true,false,'','','15 ปี หลังสิ้นสุดการวิจัย','ตามมาตรฐาน GCP','Secure Archive',$sec('Pseudonymization','Access Control/RBAC','Audit Log'),'Clinical Trial Management System','active',-6,6],
            ['MED-006','การจัดการยาและเวชภัณฑ์','ฝ่ายเภสัชกรรม','เภสัชกรหัวหน้า','บริหารการสั่งจ่าย จ่าย และบันทึกยาผู้ป่วย','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ยาที่ได้รับ'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['กระทรวงสาธารณสุข'],true,false,'','','10 ปี','ตาม พ.ร.บ.ยา','Secure Archive',$sec('Barcode System','Access Control/RBAC'),'Pharmacy Management System','active',-3,9],
            ['MED-007','การให้บริการจิตเวช','ฝ่ายจิตเวชศาสตร์','หน.จิตเวช','รักษาโรคซึมเศร้า วิตกกังวล และโรคจิต','consent',['ชื่อ-นามสกุล','ประวัติการรักษา'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],[],false,false,'','','10 ปี','ตาม พ.ร.บ.สุขภาพจิต','Shredding',$sec('Role-based Access','Encryption','Physical Access Control'),'HIS - Mental Health Module','active',-2,10],
            ['MED-008','การรายงานโรคติดต่อ','ฝ่ายระบาดวิทยา','นพ.ระบาดวิทยา','รายงานโรคติดต่อต่อ สธ. ตามกฎหมาย','legal_obligation',['ชื่อ-นามสกุล','วันเกิด','ที่อยู่','ข้อมูลสุขภาพ'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['กรมควบคุมโรค','WHO'],true,false,'','','10 ปี','ตาม พ.ร.บ.โรคติดต่อ','Secure Archive',$sec('Encryption','Secure File Transfer'),'R506 Reporting System','active',-1,11],
            ['MED-009','การเก็บตัวอย่างและตรวจ Lab','ห้อง Lab','หน.ห้องปฏิบัติการ','เก็บตัวอย่างเลือด ปัสสาวะ และตรวจวิเคราะห์','consent',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ผลตรวจ Lab'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['บริษัท Lab ภายนอก'],true,false,'','','5 ปี','','Shredding',$sec('Barcode','Role-based Access','Encryption'),'LIS (Lab Information System)','active',-4,8],
            ['MED-010','การถ่ายภาพทางรังสีวิทยา (X-Ray/CT/MRI)','ฝ่ายรังสีวิทยา','รังสีแพทย์','บันทึกและรายงานผลภาพทางการแพทย์','consent',['ชื่อ-นามสกุล','ภาพถ่าย','ข้อมูลสุขภาพ'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['โรงพยาบาลต้นทาง (กรณี Refer)'],true,false,'','','10 ปี','','Secure Archive',$sec('PACS Access Control','Encryption'),'PACS, RIS','active',-3,9],
            ['MED-011','การส่งผลตรวจทาง SMS/Email','ฝ่าย IT','หน. IT','แจ้งผลตรวจแก่ผู้ป่วยผ่านช่องทางดิจิทัล','consent',['เบอร์โทรศัพท์','อีเมล','ผลตรวจ Lab'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['SMS Gateway','Email Provider'],true,false,'','','1 ปี','','Secure Delete',$sec('Encryption','HTTPS/TLS'),'Patient Portal','active',-1,11],
            ['MED-012','การให้บริการ Telemedicine','ฝ่าย Digital Health','ผจก.ดิจิทัล','พบแพทย์ออนไลน์ผ่าน Video Call','consent',['ชื่อ-นามสกุล','ข้อมูลสุขภาพ','IP Address'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['ผู้ให้บริการ Cloud Video'],true,true,'สิงคโปร์','Data Processing Agreement','5 ปี','','Secure Delete',$sec('E2E Encryption','MFA','Audit Log'),'Zoom Healthcare, HIS','active',-2,10],
            ['MED-013','การบริหารงานบุคลากรการแพทย์','ฝ่าย HR','ผจก. HR','บริหารสัญญาจ้าง ใบอนุญาตประกอบวิชาชีพ CPD','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','เงินเดือน','ใบอนุญาตวิชาชีพ'],['พนักงาน'],false,[],['กรมสรรพากร','ประกันสังคม'],true,false,'','','10 ปี','','Secure Archive',$sec('Access Control/RBAC','Encryption'),'SAP HR, HRMS','active',-5,7],
            ['MED-014','การจัดการอุปกรณ์การแพทย์','ฝ่ายวิศวกรรมการแพทย์','วิศวกรชีวการแพทย์','บำรุงรักษาและสอบเทียบอุปกรณ์การแพทย์','legitimate_interest',['ชื่อ-นามสกุล','อีเมล'],['พนักงาน','คู่ค้า/ซัพพลายเออร์'],false,[],['ผู้ผลิตอุปกรณ์การแพทย์'],true,false,'','','5 ปี หลังหมดอายุอุปกรณ์','','Secure Delete',$sec('Access Control/RBAC'),'CMMS','active',-3,9],
            ['MED-015','การเบิกสิทธิ์หลักประกันสุขภาพ (บัตรทอง)','ฝ่ายการเงิน','ผจก.การเงิน','เบิกค่ารักษาจาก สปสช. สำหรับผู้มีสิทธิ์บัตรทอง','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ข้อมูลสุขภาพ'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['สปสช.'],true,false,'','','7 ปี','ตามระเบียบ สปสช.','Secure Archive',$sec('Encryption','Secure File Transfer'),'e-Claim, HIS','active',-6,6],
            ['MED-016','การตรวจสุขภาพประจำปี','ฝ่ายเวชศาสตร์ป้องกัน','นพ.เวชศาสตร์ป้องกัน','โปรแกรมตรวจสุขภาพประจำปีสำหรับบุคคล/องค์กร','consent',['ชื่อ-นามสกุล','วันเกิด','ข้อมูลสุขภาพ'],['ลูกค้าทั่วไป','พนักงาน'],true,['ข้อมูลสุขภาพ/การแพทย์'],['บริษัทต้นสังกัด (กรณีองค์กร)'],true,false,'','','5 ปี','','Shredding',$sec('Role-based Access','Encryption'),'Health Check System','active',-2,10],
            ['MED-017','การให้บริการธนาคารเลือด','ฝ่ายธนาคารเลือด','หน.ธนาคารเลือด','เก็บ ทดสอบ และจ่ายโลหิตสำหรับการรักษา','consent',['ชื่อ-นามสกุล','เลขบัตรประชาชน','หมู่เลือด'],['ผู้ป่วย','ผู้บริจาคโลหิต'],true,['ข้อมูลสุขภาพ/การแพทย์'],['ศูนย์บริการโลหิตแห่งชาติ'],true,false,'','','5 ปี หลังจ่ายโลหิต','ตาม พ.ร.บ.โรคติดต่อ','Secure Archive',$sec('Barcode','Role-based Access'),'Blood Bank System','active',-4,8],
            ['MED-018','การส่งต่อผู้ป่วย (Refer)','ฝ่ายเวชระเบียน','หน.เวชระเบียน','ส่งข้อมูลผู้ป่วยไปยังโรงพยาบาลอื่น','consent',['ชื่อ-นามสกุล','ข้อมูลสุขภาพ','ประวัติการรักษา'],['ผู้ป่วย'],true,['ข้อมูลสุขภาพ/การแพทย์'],['โรงพยาบาลปลายทาง'],true,false,'','','5 ปี','','Secure Transfer',$sec('Encryption','Secure File Transfer','Audit Log'),'HIS, Refer System','active',-1,11],
            ['MED-019','การตรวจพันธุกรรม (Genetic Testing)','ฝ่ายพันธุศาสตร์','นพ.พันธุศาสตร์','ตรวจหาความเสี่ยงโรคทางพันธุกรรม','consent',['ชื่อ-นามสกุล','ข้อมูลพันธุกรรม'],['ผู้ป่วย'],true,['ข้อมูลพันธุกรรม','ข้อมูลสุขภาพ/การแพทย์'],['ห้อง Lab พันธุกรรม'],true,false,'','','20 ปี','ตามมาตรฐานสากล','Secure Archive',$sec('Encryption','Physical Access Control','Role-based Access'),'Genetic Data System','active',-3,9],
            ['MED-020','การจัดการความปลอดภัยระบบ HIS','ฝ่าย IT','CIO','ดูแลความปลอดภัยระบบสารสนเทศโรงพยาบาล','legitimate_interest',['IP Address','Audit Log'],['พนักงาน'],false,[],[],false,false,'','','3 ปี','','Secure Delete',$sec('Firewall','Intrusion Detection (IDS/IPS)','Audit Log','Vulnerability Assessment'),'SIEM, WAF','active',-2,10],
        ];

        // ── INSURANCE (20 records, org 3, created_by 9) ───────────────────────
        $insurance = [
            ['INS-001','การรับประกันชีวิตรายใหม่','ฝ่ายรับประกัน','หน.รับประกัน','วิเคราะห์และรับประกันชีวิตลูกค้าใหม่','contract',['ชื่อ-นามสกุล','วันเกิด','เลขบัตรประชาชน','ข้อมูลสุขภาพ'],['ลูกค้าทั่วไป'],true,['ข้อมูลสุขภาพ/การแพทย์'],['แพทย์ตรวจสุขภาพ','Reinsurer'],true,false,'','','ตลอดอายุกรมธรรม์ + 10 ปี','ตาม พ.ร.บ.ประกันชีวิต','Secure Archive',$sec('Encryption','Access Control/RBAC','Audit Log'),'Insurance Core System','active',-3,9],
            ['INS-002','การประเมินความเสี่ยง (Underwriting)','ฝ่าย Underwriting','Chief Underwriter','ประเมินความเสี่ยงก่อนรับประกัน','contract',['ชื่อ-นามสกุล','อาชีพ','ประวัติสุขภาพ','ข้อมูลการเงิน'],['ลูกค้าทั่วไป'],true,['ข้อมูลสุขภาพ/การแพทย์'],['บริษัท Reinsurance','แพทย์'],true,false,'','','10 ปี','','Secure Archive',$sec('Encryption','Role-based Access'),'Underwriting System','active',-2,10],
            ['INS-003','การเคลมประกันชีวิต','ฝ่ายสินไหม','ผจก.สินไหม','รับและพิจารณาการเรียกร้องสินไหมมรณกรรม','contract',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ข้อมูลสุขภาพ','ทายาท'],['ลูกค้าทั่วไป'],true,['ข้อมูลสุขภาพ/การแพทย์'],['โรงพยาบาล','แพทย์นิติเวช'],true,false,'','','10 ปี หลังจ่ายสินไหม','ตาม พ.ร.บ.ประกันชีวิต','Secure Archive',$sec('Encryption','Audit Log','Role-based Access'),'Claims Management System','active',-4,8],
            ['INS-004','การบริหารกรมธรรม์ประกันชีวิต','ฝ่ายบริการลูกค้า','ผจก.บริการ','จัดการการเปลี่ยนแปลงและต่ออายุกรมธรรม์','contract',['ชื่อ-นามสกุล','ที่อยู่','เบอร์โทรศัพท์','อีเมล'],['ลูกค้าทั่วไป'],false,[],[],false,false,'','','ตลอดอายุกรมธรรม์ + 10 ปี','','Secure Archive',$sec('HTTPS/TLS','Access Control/RBAC'),'Policy Administration System','active',-1,11],
            ['INS-005','การเก็บเบี้ยประกันอัตโนมัติ','ฝ่ายการเงิน','CFO','หักเบี้ยประกันอัตโนมัติจากบัญชีธนาคาร','contract',['ชื่อ-นามสกุล','บัญชีธนาคาร','เลขบัตรเครดิต'],['ลูกค้าทั่วไป'],false,[],['ธนาคาร','Payment Gateway'],true,false,'','','5 ปี','ตาม พ.ร.บ.ประกันชีวิต','Secure Archive',$sec('PCI DSS','Encryption','Tokenization'),'Payment System, Core','active',-3,9],
            ['INS-006','การรับประกันสุขภาพกลุ่ม','ฝ่ายรับประกันกลุ่ม','หน.รับประกันกลุ่ม','รับประกันสุขภาพสำหรับพนักงานองค์กร','contract',['ชื่อ-นามสกุล','วันเกิด','ข้อมูลสุขภาพ'],['พนักงาน'],true,['ข้อมูลสุขภาพ/การแพทย์'],['HR บริษัทคู่สัญญา','โรงพยาบาลในเครือข่าย'],true,false,'','','5 ปี หลังสิ้นสุดกรมธรรม์','','Secure Archive',$sec('Encryption','Role-based Access'),'Group Insurance System','active',-5,7],
            ['INS-007','การเคลมประกันสุขภาพ','ฝ่ายสินไหมสุขภาพ','ผจก.สินไหมสุขภาพ','รับและจ่ายค่ารักษาพยาบาลตามเงื่อนไขกรมธรรม์','contract',['ชื่อ-นามสกุล','ข้อมูลสุขภาพ','ใบเสร็จ'],['ลูกค้าทั่วไป'],true,['ข้อมูลสุขภาพ/การแพทย์'],['โรงพยาบาล'],true,false,'','','7 ปี','','Secure Archive',$sec('Encryption','Audit Log'),'Health Claims System','active',-2,10],
            ['INS-008','การตรวจสอบสุขภาพก่อนรับประกัน','ฝ่ายแพทย์','หน.แพทย์','ตรวจสุขภาพลูกค้าก่อนอนุมัติกรมธรรม์','consent',['ชื่อ-นามสกุล','ข้อมูลสุขภาพ','ผลตรวจ Lab'],['ลูกค้าทั่วไป'],true,['ข้อมูลสุขภาพ/การแพทย์'],['คลินิกตรวจสุขภาพ'],true,false,'','','10 ปี','','Secure Archive',$sec('Role-based Access','Encryption'),'Medical Examination System','active',-6,6],
            ['INS-009','การประกันรถยนต์ชั้น 1','ฝ่ายรับประกันรถ','หน.รับประกันรถ','รับประกันและบริหารกรมธรรม์รถยนต์','contract',['ชื่อ-นามสกุล','เลขทะเบียนรถ','ข้อมูลประวัติขับขี่'],['ลูกค้าทั่วไป'],false,[],['กรมการขนส่งทางบก'],true,false,'','','5 ปี','','Secure Archive',$sec('Encryption','Access Control/RBAC'),'Motor Insurance System','active',-3,9],
            ['INS-010','การเคลมประกันรถยนต์','ฝ่ายสินไหมรถ','ผจก.สินไหมรถ','สำรวจและจ่ายค่าซ่อมรถ','contract',['ชื่อ-นามสกุล','ทะเบียนรถ','ข้อมูลอุบัติเหตุ'],['ลูกค้าทั่วไป'],false,[],['อู่ซ่อม','ตำรวจ'],true,false,'','','5 ปี','','Secure Archive',$sec('GPS Tracking','Encryption'),'Claims Survey System','active',-1,11],
            ['INS-011','การตรวจสอบทุจริตประกัน','ฝ่ายป้องกันการทุจริต','หน.SIU','สืบสวนและตรวจสอบการเรียกร้องที่น่าสงสัย','legitimate_interest',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ประวัติการเคลม'],['ลูกค้าทั่วไป'],false,[],[],false,false,'','','10 ปี','','Secure Delete',$sec('Encryption','Audit Log','Physical Access Control'),'SIU Investigation System','active',-4,8],
            ['INS-012','การส่งข้อมูลต่อ Reinsurer','ฝ่าย Reinsurance','หน. Reinsurance','โอนความเสี่ยงบางส่วนให้บริษัท Reinsurance','contract',['ข้อมูลสถิติผู้เอาประกัน (Anonymized)'],['ลูกค้าทั่วไป'],false,[],['Swiss Re','Munich Re'],true,true,'สวิตเซอร์แลนด์,เยอรมนี','Standard Reinsurance Agreement','10 ปี','','Secure Archive',$sec('Anonymization','Encryption','Secure File Transfer'),'Reinsurance Platform','active',-5,7],
            ['INS-013','การตลาดและขายประกัน','ฝ่ายการตลาด','CMO','แคมเปญการตลาดผ่านช่องทางต่างๆ','consent',['ชื่อ','เบอร์โทรศัพท์','อีเมล'],['ลูกค้าทั่วไป'],false,[],['ตัวแทนประกัน','นายหน้า'],true,false,'','','1 ปี หรือจนถอนความยินยอม','','Secure Delete',$sec('Data Minimization','Consent Management'),'CRM Salesforce','active',-2,10],
            ['INS-014','การบริหารตัวแทนและนายหน้า','ฝ่ายตัวแทน','หน.ตัวแทน','ลงทะเบียนและจัดการค่าคอมมิชชั่นตัวแทน','contract',['ชื่อ-นามสกุล','เลขบัตรประชาชน','บัญชีธนาคาร','ใบอนุญาตนายหน้า'],['คู่ค้า/ซัพพลายเออร์'],false,[],['กรมสรรพากร'],true,false,'','','10 ปี','ตาม พ.ร.บ.ประกันชีวิต','Secure Archive',$sec('Access Control/RBAC','Audit Log'),'Agency Management System','active',-3,9],
            ['INS-015','การประกันอุบัติเหตุส่วนบุคคล (PA)','ฝ่ายรับประกัน','หน.รับประกัน','รับประกันอุบัติเหตุและทุพพลภาพ','contract',['ชื่อ-นามสกุล','วันเกิด','อาชีพ'],['ลูกค้าทั่วไป'],false,[],[],false,false,'','','5 ปี','','Secure Archive',$sec('Encryption','Access Control/RBAC'),'Insurance Core System','active',-1,11],
            ['INS-016','การรายงานต่อ คปภ.','ฝ่ายกำกับดูแล','CCO','รายงานข้อมูลทางการเงินและสถิติต่อ คปภ.','legal_obligation',['ข้อมูลสถิติรวม (Aggregated)'],['ลูกค้าทั่วไป'],false,[],['สำนักงาน คปภ.'],true,false,'','','5 ปี','ตาม พ.ร.บ.ประกันชีวิต','Secure Archive',$sec('Audit Log','Encryption'),'Regulatory Reporting System','active',-6,6],
            ['INS-017','การบริหารทรัพยากรบุคคล','ฝ่าย HR','ผจก. HR','บริหารสัญญาจ้าง เงินเดือน สวัสดิการ','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','เงินเดือน'],['พนักงาน'],false,[],['กรมสรรพากร','ประกันสังคม'],true,false,'','','10 ปี','ตาม พ.ร.บ.คุ้มครองแรงงาน','Shredding',$sec('Access Control/RBAC','Encryption'),'HRMS','active',-2,10],
            ['INS-018','การให้บริการผ่านแอปพลิเคชัน','ฝ่าย Digital','CDO','บริการดูกรมธรรม์ แจ้งเคลม และชำระเบี้ยผ่านแอป','contract',['ชื่อ-นามสกุล','อีเมล','IP Address','Cookie/Tracking'],['ลูกค้าทั่วไป'],false,[],['Cloud Provider (AWS)'],true,true,'สหรัฐอเมริกา','SCCs, DPA','5 ปี','','Secure Delete',$sec('HTTPS/TLS','MFA','Encryption'),'Mobile App, AWS','active',-3,9],
            ['INS-019','การประกันภัยทางทะเล (Marine)','ฝ่ายรับประกันพาณิชย์','หน.รับประกันพาณิชย์','รับประกันสินค้าและเรือขนส่งทางทะเล','contract',['ชื่อบริษัท','รายละเอียดสินค้า','เส้นทางขนส่ง'],['คู่ค้า/ซัพพลายเออร์'],false,[],['Lloyd\'s of London','Surveyor'],true,true,'สหราชอาณาจักร','Market Agreement','5 ปี','','Secure Archive',$sec('Encryption','Access Control/RBAC'),'Marine Insurance System','active',-4,8],
            ['INS-020','การตรวจสอบ KYC/AML','ฝ่าย Compliance','CCO','ตรวจสอบตัวตนและป้องกันฟอกเงิน','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ข้อมูลการเงิน'],['ลูกค้าทั่วไป'],false,[],['ธนาคารแห่งประเทศไทย','ปปง.'],true,false,'','','10 ปี ตาม พ.ร.บ.ฟอกเงิน','ตาม พ.ร.บ.ป้องกันและปราบปรามการฟอกเงิน','Secure Archive',$sec('KYC System','Audit Log','Encryption'),'KYC/AML Platform','active',-1,11],
        ];

        // ── CONSTRUCTION (20 records, org 1, created_by 2) ────────────────────
        $construction = [
            ['CON-001','การบริหารสัญญาก่อสร้าง','ฝ่ายสัญญา','ผจก.สัญญา','จัดทำและบริหารสัญญากับเจ้าของโครงการ','contract',['ชื่อ-นามสกุล','ที่อยู่','เลขบัตรประชาชน'],['คู่ค้า/ซัพพลายเออร์'],false,[],[],false,false,'','','10 ปี หลังสิ้นสุดสัญญา','ตามอายุความ','Shredding',$sec('Access Control/RBAC','Audit Log'),'Contract Management System','active',-4,8],
            ['CON-002','การจัดการแรงงานก่อสร้าง','ฝ่าย HR โครงการ','ผจก. HR โครงการ','บริหารแรงงานและลูกจ้างชั่วคราวในไซต์งาน','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','สัญชาติ','ที่อยู่'],['พนักงาน'],false,[],['กระทรวงแรงงาน','ประกันสังคม'],true,false,'','','5 ปี หลังสิ้นสุดสัญญาจ้าง','ตาม พ.ร.บ.คุ้มครองแรงงาน','Shredding',$sec('Access Control/RBAC'),'HR Management System','active',-3,9],
            ['CON-003','การจัดการแรงงานต่างด้าว','ฝ่าย HR','หน. HR แรงงานต่างด้าว','บริหารใบอนุญาตทำงานแรงงานต่างชาติ','legal_obligation',['ชื่อ-นามสกุล','สัญชาติ','หนังสือเดินทาง','Visa/WP'],['พนักงาน'],false,[],['กรมแรงงาน','ตรวจคนเข้าเมือง'],true,false,'','','ตลอดระยะเวลาจ้าง + 2 ปี','ตาม พ.ร.บ.การทำงานของคนต่างด้าว','Shredding',$sec('Physical Access Control','Access Control/RBAC'),'Work Permit System','active',-2,10],
            ['CON-004','การบริหารซัพคอนแทรกเตอร์','ฝ่ายจัดซื้อ','ผจก.จัดซื้อ','คัดเลือกและบริหารผู้รับเหมาช่วง','contract',['ชื่อบริษัท','ผู้ติดต่อ','เลขทะเบียนนิติบุคคล'],['คู่ค้า/ซัพพลายเออร์'],false,[],[],false,false,'','','5 ปี','','Shredding',$sec('Access Control/RBAC'),'Vendor Management','active',-5,7],
            ['CON-005','การประเมินความปลอดภัยในไซต์งาน','ฝ่ายความปลอดภัย','จป.วิชาชีพ','ตรวจสอบและบันทึกความปลอดภัยตาม กม.','legal_obligation',['ชื่อ-นามสกุล','ผลการตรวจสุขภาพ'],['พนักงาน'],false,[],['กรมสวัสดิการและคุ้มครองแรงงาน'],true,false,'','','5 ปี','ตาม พ.ร.บ.ความปลอดภัย','Shredding',$sec('Audit Log','Access Control/RBAC'),'Safety Management System','active',-1,11],
            ['CON-006','การบันทึกอุบัติเหตุในงานก่อสร้าง','ฝ่ายความปลอดภัย','จป.วิชาชีพ','บันทึกและรายงานอุบัติเหตุ เจ็บป่วยจากงาน','legal_obligation',['ชื่อ-นามสกุล','ข้อมูลสุขภาพ','รายละเอียดอุบัติเหตุ'],['พนักงาน'],true,['ข้อมูลสุขภาพ/การแพทย์'],['กรมแรงงาน','กองทุนเงินทดแทน'],true,false,'','','5 ปี','ตาม พ.ร.บ.เงินทดแทน','Secure Archive',$sec('Access Control/RBAC','Audit Log'),'Accident Reporting System','active',-3,9],
            ['CON-007','การจัดการเงินเดือนและค่าแรง','ฝ่ายการเงิน','CFO','คำนวณและจ่ายค่าแรงรายวัน/รายเดือน','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','บัญชีธนาคาร','ค่าแรง'],['พนักงาน'],false,[],['กรมสรรพากร','ธนาคาร'],true,false,'','','7 ปี ตาม พ.ร.บ.บัญชี','','Shredding',$sec('Encryption','Access Control/RBAC'),'Payroll System','active',-2,10],
            ['CON-008','การบันทึกชั่วโมงทำงาน','ฝ่ายโครงการ','PM','บันทึกเวลาเข้า-ออกงานในไซต์ด้วยลายนิ้วมือ','legal_obligation',['ชื่อ-นามสกุล','ข้อมูลชีวมิติ (ลายนิ้วมือ/ใบหน้า)'],['พนักงาน'],true,['ข้อมูลชีวมิติ (ลายนิ้วมือ/ใบหน้า)'],[],false,false,'','','1 ปี หลังสิ้นสุดโครงการ','ตาม พ.ร.บ.คุ้มครองแรงงาน','Secure Delete',$sec('Biometric Encryption','Physical Access Control'),'Time Attendance System','active',-4,8],
            ['CON-009','การบริหารโครงการ (Project Management)','ฝ่ายโครงการ','PM','วางแผนและติดตามความคืบหน้าโครงการ','contract',['ชื่อ-นามสกุล','อีเมล','เบอร์โทรศัพท์'],['คู่ค้า/ซัพพลายเออร์','พนักงาน'],false,[],[],false,false,'','','5 ปี หลังสิ้นสุดโครงการ','','Secure Delete',$sec('Access Control/RBAC'),'MS Project, Primavera','active',-1,11],
            ['CON-010','การจัดการเอกสารแบบก่อสร้าง','ฝ่ายวิศวกรรม','หน.วิศวกรรม','จัดเก็บและควบคุมแบบก่อสร้างและเอกสารโครงการ','contract',['ชื่อ-นามสกุล','อีเมล'],['คู่ค้า/ซัพพลายเออร์','พนักงาน'],false,[],[],false,false,'','','10 ปี ตามมาตรฐานวิชาชีพ','','Shredding',$sec('Access Control/RBAC','Version Control'),'Autodesk BIM 360','active',-2,10],
            ['CON-011','การตรวจรับงานและออกใบรับรอง','ฝ่ายควบคุมงาน','QC Manager','ตรวจสอบและรับรองคุณภาพงานก่อสร้าง','contract',['ชื่อ-นามสกุล','ใบอนุญาตวิชาชีพ'],['พนักงาน','คู่ค้า/ซัพพลายเออร์'],false,[],[],false,false,'','','10 ปี','','Shredding',$sec('Audit Log','Access Control/RBAC'),'QC Management System','active',-3,9],
            ['CON-012','การจัดการอุปกรณ์และเครื่องจักร','ฝ่ายเครื่องจักร','หน.เครื่องจักร','บำรุงรักษาและติดตามเครื่องจักรในไซต์','legitimate_interest',['ชื่อ-นามสกุล','ใบขับขี่เครื่องจักร'],['พนักงาน'],false,[],[],false,false,'','','5 ปี','','Secure Delete',$sec('GPS Tracking','Access Control/RBAC'),'Equipment Management System','active',-4,8],
            ['CON-013','การจัดซื้อวัสดุก่อสร้าง','ฝ่ายจัดซื้อ','ผจก.จัดซื้อ','จัดซื้อและตรวจรับวัสดุก่อสร้าง','contract',['ชื่อบริษัท','ผู้ติดต่อ','เลขทะเบียนนิติบุคคล'],['คู่ค้า/ซัพพลายเออร์'],false,[],[],false,false,'','','5 ปี','ตาม พ.ร.บ.บัญชี','Shredding',$sec('Access Control/RBAC'),'ERP Procurement','active',-5,7],
            ['CON-014','การตรวจสอบประวัติแรงงาน (Background Check)','ฝ่าย HR','ผจก. HR','ตรวจสอบประวัติอาชญากรรมก่อนจ้างงาน','legitimate_interest',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ประวัติอาชญากรรม'],['ผู้สมัครงาน'],true,['ประวัติอาชญากรรม'],['กองทะเบียนประวัติอาชญากร'],true,false,'','','1 ปี หลังสิ้นสุดกระบวนการ','','Secure Delete',$sec('Access Control/RBAC','Encryption'),'Background Check API','active',-2,10],
            ['CON-015','การบริหารประกันโครงการ (CAR)','ฝ่ายการเงิน','CFO','จัดการกรมธรรม์ประกันภัยงานก่อสร้าง','contract',['ชื่อ-นามสกุล','ข้อมูลโครงการ'],['คู่ค้า/ซัพพลายเออร์'],false,[],['บริษัทประกัน'],true,false,'','','ตลอดอายุโครงการ + 2 ปี','','Shredding',$sec('Access Control/RBAC'),'Insurance Management','active',-1,11],
            ['CON-016','การบันทึก CCTV ในไซต์งาน','ฝ่ายความปลอดภัย','จป.วิชาชีพ','ดูแลความปลอดภัยและป้องกันการโจรกรรมในไซต์','legitimate_interest',['ภาพถ่าย'],['พนักงาน','บุคคลภายนอกอื่นๆ'],false,[],[],false,false,'','','30 วัน','ยกเว้นกรณีเกิดเหตุ','Overwrite',$sec('Physical Access Control'),'NVR CCTV System','active',-3,9],
            ['CON-017','การรายงานต่อหน่วยงานราชการ','ฝ่ายกฎหมาย','นิติกร','ยื่นเอกสารราชการและรายงานโครงการต่อ อบท.','legal_obligation',['ชื่อ-นามสกุล','เลขทะเบียนนิติบุคคล'],['คู่ค้า/ซัพพลายเออร์'],false,[],['อบต.','กรมโยธาธิการ'],true,false,'','','10 ปี','ตามกฎหมายก่อสร้าง','Shredding',$sec('Audit Log'),'Document Management System','active',-6,6],
            ['CON-018','การจัดการสวัสดิการแรงงาน','ฝ่าย HR','ผจก. HR','บริหารสวัสดิการ ที่พัก อาหาร แรงงาน','legal_obligation',['ชื่อ-นามสกุล','ที่อยู่','ข้อมูลครอบครัว'],['พนักงาน'],false,[],[],false,false,'','','5 ปี','ตาม พ.ร.บ.คุ้มครองแรงงาน','Shredding',$sec('Access Control/RBAC'),'HR Welfare System','active',-2,10],
            ['CON-019','การฝึกอบรมความปลอดภัย','ฝ่ายความปลอดภัย','จป.วิชาชีพ','อบรม Safety Induction และอบรมประจำปี','legal_obligation',['ชื่อ-นามสกุล','ผลการทดสอบ'],['พนักงาน'],false,[],[],false,false,'','','3 ปี','ตาม พ.ร.บ.ความปลอดภัย','Shredding',$sec('Access Control/RBAC'),'LMS Training System','active',-4,8],
            ['CON-020','การจัดการสัญญาเช่าที่ดินไซต์','ฝ่ายสัญญา','ผจก.สัญญา','เช่าพื้นที่ก่อสร้างและบริหารสัญญาที่ดิน','contract',['ชื่อ-นามสกุล','เลขโฉนดที่ดิน','ข้อมูลทรัพย์สิน'],['บุคคลภายนอกอื่นๆ'],false,[],[],false,false,'','','ตลอดอายุสัญญา + 5 ปี','','Shredding',$sec('Access Control/RBAC'),'Contract Management System','draft',0,12],
        ];

        // ── GOVERNMENT (20 records, org 2, created_by 7) ─────────────────────
        $government = [
            ['GOV-001','การให้บริการทะเบียนราษฎร','ฝ่ายทะเบียน','หน.ฝ่ายทะเบียน','ออกบัตรประชาชน สูติบัตร มรณบัตร','legal_obligation',['ชื่อ-นามสกุล','วันเกิด','เลขบัตรประชาชน','ที่อยู่'],['บุคคลภายนอกอื่นๆ'],false,[],['กรมการปกครอง'],true,false,'','','ตลอดชีวิต','ตาม พ.ร.บ.ทะเบียนราษฎร','Secure Archive',$sec('Role-based Access','Audit Log','Encryption'),'DOPA System','active',-3,9],
            ['GOV-002','การจัดเก็บภาษีท้องถิ่น','ฝ่ายจัดเก็บรายได้','หน.จัดเก็บรายได้','จัดเก็บภาษีที่ดิน ภาษีป้าย และค่าธรรมเนียม','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ข้อมูลทรัพย์สิน'],['บุคคลภายนอกอื่นๆ'],false,[],['กรมสรรพากร','กรมที่ดิน'],true,false,'','','10 ปี','ตาม พ.ร.บ.ภาษีที่ดินและสิ่งปลูกสร้าง','Secure Archive',$sec('Role-based Access','Audit Log'),'Revenue Collection System','active',-2,10],
            ['GOV-003','การออกใบอนุญาตก่อสร้าง','ฝ่ายโยธา','หน.โยธา','รับคำขอและออกใบอนุญาตก่อสร้างอาคาร','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','เลขโฉนด'],['บุคคลภายนอกอื่นๆ'],false,[],['กรมโยธาธิการ'],true,false,'','','10 ปี','ตาม พ.ร.บ.ควบคุมอาคาร','Secure Archive',$sec('Role-based Access','Audit Log'),'Permit System','active',-4,8],
            ['GOV-004','การบริหารงานบุคคลภาครัฐ','ฝ่ายบุคลากร','หน.บุคลากร','บริหารตำแหน่ง เงินเดือน สวัสดิการข้าราชการ','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','เงินเดือน','ประวัติราชการ'],['พนักงาน'],false,[],['กรมบัญชีกลาง','ก.พ.'],true,false,'','','ตลอดชีวิต','ตาม พ.ร.บ.ระเบียบข้าราชการพลเรือน','Secure Archive',$sec('Role-based Access','Encryption','Audit Log'),'DPIS, GFMIS','active',-1,11],
            ['GOV-005','การให้บริการสวัสดิการสังคม','ฝ่ายพัฒนาสังคม','หน.พัฒนาสังคม','ลงทะเบียนและจ่ายเงินช่วยเหลือผู้มีรายได้น้อย','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','รายได้ครัวเรือน','บัญชีธนาคาร'],['บุคคลภายนอกอื่นๆ'],false,[],['กรมพัฒนาสังคม','ธนาคาร'],true,false,'','','5 ปี','ตามระเบียบสวัสดิการสังคม','Secure Archive',$sec('Encryption','Role-based Access'),'Welfare Registration System','active',-3,9],
            ['GOV-006','การจัดการร้องทุกข์ประชาชน','ฝ่ายรับเรื่องร้องเรียน','หน.รับเรื่องร้องเรียน','รับ ส่งต่อ และติดตามเรื่องร้องทุกข์','legal_obligation',['ชื่อ-นามสกุล','เบอร์โทรศัพท์','อีเมล'],['บุคคลภายนอกอื่นๆ'],false,[],['หน่วยงานที่เกี่ยวข้อง'],true,false,'','','5 ปี','ตามระเบียบร้องทุกข์','Shredding',$sec('Audit Log','Access Control/RBAC'),'Complaint Management System','active',-2,10],
            ['GOV-007','การจัดซื้อจัดจ้างภาครัฐ','ฝ่ายพัสดุ','หน.พัสดุ','ดำเนินการจัดซื้อจัดจ้างตาม พ.ร.บ.จัดซื้อฯ','legal_obligation',['ชื่อบริษัท','กรรมการผู้มีอำนาจ','เลขทะเบียนนิติบุคคล'],['คู่ค้า/ซัพพลายเออร์'],false,[],['กรมบัญชีกลาง (e-GP)'],true,false,'','','10 ปี','ตาม พ.ร.บ.จัดซื้อจัดจ้าง','Shredding',$sec('Audit Log','Access Control/RBAC'),'e-GP System','active',-5,7],
            ['GOV-008','การให้บริการด้านสาธารณสุขชุมชน','ฝ่ายสาธารณสุข','หน.สาธารณสุข','ให้บริการฉีดวัคซีนและตรวจสุขภาพชุมชน','legal_obligation',['ชื่อ-นามสกุล','วันเกิด','ข้อมูลสุขภาพ','ประวัติวัคซีน'],['บุคคลภายนอกอื่นๆ'],true,['ข้อมูลสุขภาพ/การแพทย์'],['กระทรวงสาธารณสุข','สปสช.'],true,false,'','','ตลอดชีวิต','ตาม พ.ร.บ.โรคติดต่อ','Secure Archive',$sec('Role-based Access','Encryption'),'JHCIS, HIS','active',-4,8],
            ['GOV-009','การบริหารการศึกษาในพื้นที่','ฝ่ายการศึกษา','หน.การศึกษา','บริหารทุนการศึกษา ข้อมูลนักเรียน','legal_obligation',['ชื่อ-นามสกุล','วันเกิด','ข้อมูลครอบครัว'],['นักศึกษา','บุคคลภายนอกอื่นๆ'],false,[],['กระทรวงศึกษาธิการ'],true,false,'','','10 ปี หลังจบการศึกษา','ตาม พ.ร.บ.การศึกษา','Secure Archive',$sec('Role-based Access','Audit Log'),'Education Management System','active',-2,10],
            ['GOV-010','การออกใบอนุญาตประกอบธุรกิจ','ฝ่ายเศรษฐกิจ','หน.เศรษฐกิจ','ออกและต่ออายุใบอนุญาตประกอบกิจการ','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','เลขทะเบียนนิติบุคคล'],['บุคคลภายนอกอื่นๆ'],false,[],['DBD','กรมพัฒนาธุรกิจการค้า'],true,false,'','','5 ปี หลังหมดอายุใบอนุญาต','','Shredding',$sec('Audit Log','Role-based Access'),'License Management System','active',-1,11],
            ['GOV-011','การบริหารงบประมาณและการเงิน','ฝ่ายการคลัง','หน.การคลัง','บริหารรายรับรายจ่ายและงบประมาณประจำปี','legal_obligation',['ชื่อ-นามสกุล','ข้อมูลการเงิน'],['พนักงาน','คู่ค้า/ซัพพลายเออร์'],false,[],['กรมบัญชีกลาง','สตง.'],true,false,'','','10 ปี ตาม พ.ร.บ.บัญชี','','Secure Archive',$sec('Audit Log','Role-based Access','Encryption'),'GFMIS','active',-6,6],
            ['GOV-012','การจัดการผังเมืองและสิ่งแวดล้อม','ฝ่ายผังเมือง','หน.ผังเมือง','บริหารผังเมือง EIA และสิ่งแวดล้อม','legal_obligation',['ชื่อ-นามสกุล','ข้อมูลทรัพย์สิน','ที่ตั้งโครงการ'],['บุคคลภายนอกอื่นๆ'],false,[],['กรมโยธาธิการ','สผ.'],true,false,'','','ถาวร','ตาม พ.ร.บ.ผังเมือง','Secure Archive',$sec('GIS System','Role-based Access'),'GIS, Urban Planning System','active',-3,9],
            ['GOV-013','การให้บริการด้านโครงสร้างพื้นฐาน','ฝ่ายช่าง','หน.ช่าง','บริหารงานซ่อมบำรุงถนน ไฟฟ้า ประปา','legal_obligation',['ชื่อ-นามสกุล','เบอร์โทรศัพท์','ที่อยู่'],['บุคคลภายนอกอื่นๆ'],false,[],[],false,false,'','','3 ปี','','Shredding',$sec('Audit Log'),'Work Order System','active',-2,10],
            ['GOV-014','การดำเนินคดีและบังคับใช้กฎหมาย','ฝ่ายนิติการ','นิติกร','ดำเนินคดีทางปกครองและบังคับใช้กฎหมาย','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','ข้อมูลคดี'],['บุคคลภายนอกอื่นๆ'],false,[],['ศาลปกครอง','สำนักงานอัยการ'],true,false,'','','10 ปี หลังคดีสิ้นสุด','ตาม พ.ร.บ.วิธีปฏิบัติราชการทางปกครอง','Secure Archive',$sec('Role-based Access','Audit Log','Physical Access Control'),'Case Management System','active',-4,8],
            ['GOV-015','การเลือกตั้งท้องถิ่น','ฝ่ายเลือกตั้ง','หน.เลือกตั้ง','บริหารจัดการการเลือกตั้ง อบต./อบจ.','legal_obligation',['ชื่อ-นามสกุล','วันเกิด','เลขบัตรประชาชน','ที่อยู่'],['บุคคลภายนอกอื่นๆ'],false,[],['กกต.'],true,false,'','','ถาวร','ตาม พ.ร.บ.การเลือกตั้ง','Secure Archive',$sec('Role-based Access','Audit Log','Physical Access Control'),'Election Management System','active',-1,11],
            ['GOV-016','การบริหารที่ดินสาธารณะ','ฝ่ายที่ดิน','หน.ที่ดิน','จัดสรรและบริหารที่ดินสาธารณะ','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','เลขโฉนด'],['บุคคลภายนอกอื่นๆ'],false,[],['กรมที่ดิน'],true,false,'','','ถาวร','','Secure Archive',$sec('Role-based Access','GIS'),'Land Management System','active',-3,9],
            ['GOV-017','การจัดการข้อมูลประชากร','ฝ่ายแผนและสถิติ','หน.แผน','วิเคราะห์ข้อมูลประชากรเพื่อวางแผน','public_interest',['ข้อมูลสถิติรวม (Aggregated)'],['บุคคลภายนอกอื่นๆ'],false,[],['สำนักงานสถิติแห่งชาติ'],true,false,'','','ถาวร','ตาม พ.ร.บ.สถิติ','Anonymize',$sec('Anonymization','Access Control/RBAC'),'Statistical Analysis System','active',-5,7],
            ['GOV-018','การให้ทุนและเงินช่วยเหลือ','ฝ่ายสวัสดิการ','หน.สวัสดิการ','พิจารณาและจ่ายทุนการศึกษา เบี้ยผู้สูงอายุ','legal_obligation',['ชื่อ-นามสกุล','เลขบัตรประชาชน','บัญชีธนาคาร'],['บุคคลภายนอกอื่นๆ'],false,[],['ธนาคาร','กระทรวงการคลัง'],true,false,'','','5 ปี','','Shredding',$sec('Encryption','Role-based Access','Audit Log'),'Subsidy Management System','active',-2,10],
            ['GOV-019','การบริหารข้อมูลสาธารณะ (Open Data)','ฝ่าย IT','CIO','เปิดเผยข้อมูลรัฐต่อสาธารณะตาม พ.ร.บ.ข้อมูลข่าวสาร','public_interest',['ข้อมูลสถิติรวม (Anonymized)'],['บุคคลภายนอกอื่นๆ'],false,[],['DGA (รัฐบาลดิจิทัล)'],true,false,'','','ถาวร','ตาม พ.ร.บ.ข้อมูลข่าวสารของราชการ','Anonymize',$sec('Anonymization','Open Data Standard'),'Open Data Platform','active',-1,11],
            ['GOV-020','การรักษาความมั่นคงปลอดภัยไซเบอร์','ฝ่าย IT','CISO','ป้องกันและตอบสนองภัยคุกคามทางไซเบอร์','legal_obligation',['IP Address','Audit Log'],['พนักงาน'],false,[],['สกมช. (NCSA)'],true,false,'','','3 ปี','ตาม พ.ร.บ.ไซเบอร์','Secure Delete',$sec('Firewall','Intrusion Detection (IDS/IPS)','SIEM','Vulnerability Assessment'),'SIEM, SOC Platform','active',-4,8],
        ];

        // ── INSERT ALL ────────────────────────────────────────────────────────
        $allSets = [
            ['data' => $retail,       'org' => 1, 'user' => 2],
            ['data' => $hospital,     'org' => 1, 'user' => 2],
            ['data' => $insurance,    'org' => 1, 'user' => 2],
            ['data' => $construction, 'org' => 1, 'user' => 2],
            ['data' => $government,   'org' => 1, 'user' => 2],
        ];

        $statusCycle   = ['active','active','active','active','under_review','draft'];
        $reviewOffsets = [9, 10, 11, 12, -1, -2, 6, 8]; // months from now
        $total = 0;

        foreach ($allSets as $set) {
            foreach ($set['data'] as $i => $r) {
                // r = [code, name, dept, owner, purpose, legal_basis,
                //      data_cats[], subject_types[], has_sensitive, sensitive_cats[],
                //      recipients[], 3rd_party, cross_border, cb_countries, cb_safeguards,
                //      retention, retention_criteria, deletion, security[], system,
                //      status, reviewed_months_ago, next_review_months]
                [$code,$name,$dept,$owner,$purpose,$basis,
                 $dataCats,$subjTypes,$hasSensitive,$sensitiveCats,
                 $recipients,$thirdParty,$crossBorder,$cbCountries,$cbSafeguards,
                 $retention,$retCriteria,$deletion,$security,$system,
                 $status,$reviewedAgo,$nextReview] = $r;

                $lastReviewed  = $reviewedAgo > 0 ? $date(-$reviewedAgo) : null;
                $nextReviewDt  = $date($nextReview);

                RopaRecord::create([
                    'organization_id'                => $set['org'],
                    'process_name'                   => $name,
                    'process_code'                   => $code,
                    'department'                     => $dept,
                    'process_owner'                  => $owner,
                    'role'                           => 'controller',
                    'purpose'                        => $purpose,
                    'legal_basis'                    => $basis,
                    'data_categories'                => $dataCats,
                    'data_subject_types'             => $subjTypes,
                    'has_sensitive_data'             => $hasSensitive,
                    'sensitive_data_categories'      => $sensitiveCats ?: null,
                    'recipients'                     => $recipients,
                    'third_party_transfer'           => $thirdParty,
                    'cross_border_transfer'          => $crossBorder,
                    'cross_border_countries'         => $cbCountries ?: null,
                    'cross_border_safeguards'        => $cbSafeguards ?: null,
                    'retention_period'               => $retention,
                    'retention_criteria'             => $retCriteria ?: null,
                    'deletion_method'                => $deletion ?: null,
                    'security_measures'              => $security,
                    'system_used'                    => $system ?: null,
                    'status'                         => $status,
                    'last_reviewed_at'               => $lastReviewed,
                    'next_review_date'               => $nextReviewDt,
                    'created_by'                     => $set['user'],
                ]);
                $total++;
            }
        }

        $this->command->info("✅ ROPA seeded: {$total} records (Retail 20 + Hospital 20 + Insurance 20 + Construction 20 + Government 20)");
    }
}
